# The URL the site will be built for
base_url = "https://www.cyanogenoid.com"

theme = "terminimal"
default_language = "en"

# Optional: enable tags
taxonomies = [
    { name = "tags" },
    { name = "categories" },
]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Syntax highlighting (Giallo)
[markdown.highlighting]
theme = "one-dark-pro"

[extra]
# Put all your custom variables here
accent_color = "blue"
author = "Yan Zhang"
logo_text = "Cyanogenoid"

enable_post_view_navigation = false
post_view_navigation_prompt = ""

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    
    {name = "about me", url = "$BASE_URL"},
    {name = "papers", url = "$BASE_URL/papers"},
    {name = "fun", url = "$BASE_URL/fun"},
]
